<div style=" font-size:14px;  ">
	<div style="padding: 10px 0px;">
		<div style="padding: 2px 20px 30px;">
			<p>亲爱的 <span style="color: rgb(196, 0, 0);">$username$</span>,您好！</p>
			<p>你的验证码为：$msg$,有效期为30分钟，为了您的账户安全请不要告诉他人</p>
			<p>感谢您光临$webname$用户中心，我们的宗旨：做中国最安全，用户最喜欢，社会责任心最强的网贷服务平台！  <br>现在就登录吧!
			<a title="点击登录$webname$用户中心" href="$host$" target="_blank" swaped="true">$host$</a> 
			</p>
			<p style="text-align: right;"><br>$webname$用户中心 敬启</p>
			<p><br>此为自动发送邮件，请勿直接回复！ 如有问题请联系客服人员</p>
		</div>
	</div>
</div>