<div style=" font-size:14px;  ">
	<div style="padding: 10px 0px;">
		<!--
		<h1 style="padding: 0px 15px; margin: 0px; overflow: hidden; height: 48px;">
			<a title="$webname$用户中心" href="http://$host$/" target="_blank" swaped="true">
			<img style="border-width: 0px; padding: 0px; margin: 0px;" alt="$webname$用户中心" src="http://$host$/data/images/base/email_logo.png" height="48" width="208"></a>
		</h1>
		-->
		
		<div style="padding: 2px 20px 30px;">
			<p>尊敬的用户 $endTime$<span style="color: rgb(196, 0, 0);">$username$</span>:</p>
			<p>       您好!</p>
			<p>       您投资的【$borrowname$】借款标，金额￥$account$,年利率:$apr$%。 </p>
			<p>       复审通过,请查看     </p>
             
			
			 
<p>       感谢您对我们的支持与关注。</p></br>
<br><span style="color: rgb(153, 153, 153);">      感谢您光临国控小微，我们致力于打造中国最诚信可靠的P 2 P（Peer to Peer 或 Person to Person，即点对点，
个人对个人）网络投融资平台，我们的经营目标是以我们优质、专业的服务为理财者轻松、方便地获得满意的收益，为借款者快捷简便地取得经营发展的资金，努力为金融行业的发展贡献自己的力量！ </span></p>
<p>      现在就登录吧!<a title="点击登录" href="$host$" target="_blank" swaped="true">$host$</a> 
			</p>
			<p style="text-align: right;"><br>$webname$  敬启</p>
			<p><br>此为自动发送邮件，请勿直接回复！请您登录国控小微网站 ，致电在线客服或致电$fuwutel$（测试）</p>
		</div>
	</div>
</div>        